[Feature] 여행 정보를 등록, 수정, 삭제한다.
FC-BE-ToyProject-Team6/KDT_Y_BE_Toy_Project2_DEV pull request #13
Opened 2023-10-24 09:10 UTC by ghrltjdtprbs

## [Feature] 여행 정보를 등록, 수정, 삭제한다.

여행 정보를 등록, 수정, 삭제하는 로직을 구현했습니다.

- 여행 등록시 createdAt, updatedAt 갱신 / 입력한 데이터 저장
- 여행 수정시 updatedAt 갱신 / 수정된 데이터 저장
- 여행 삭제시 updatedAt, deletedAt 갱신, is_deleted 값 true로 변경

-------
- member 도메인이 구현이 안되어서 memberid값을 null로 받고 있습니다.
- isDomestic 값을 true로 보내도 계속 false로 반환이 되는데, 원인을 모르겠습니다... 혹시 아시는 분은 코드 리뷰로 남겨주세요..

<img width="418" alt="image" src="https://github.com/FC-BE-ToyProject-Team6/KDT_Y_BE_Toy_Project2_DEV/assets/105612931/f79f3c96-18c0-46ca-aa56-f1f1e62fec8f">

2023-10-24 09:16 UTC, decten commented
확인했습니다, 수고하셨습니다👍
isDomestic은 풀리퀘 받은 후 확인 해보겠습니다!

2023-10-24 11:05 UTC, whdgns5059 requested changes
확인해보니 Lombok 과 RequetBody 의 get문제 때문 이네요. 수정하시고 배포하시면 될 것 같습니다

수고하셧어요!

2023-10-24 11:05 UTC, whdgns5059 commented on src/main/java/com/fastcampus/toyproject/domain/trip/dto/TripDTO.java
> +@Setter
DTO에 Setter를 쓰는건 위험한걸로 알고 있습니다. 
@Builder @AllArgsConstructor @NoArgsConstructor 를 이용하는게 좋을 것 같습니다.

2023-10-24 11:05 UTC, whdgns5059 commented on src/main/java/com/fastcampus/toyproject/domain/trip/dto/TripDTO.java
> +    private boolean isDomestic;
isDomestic의 경우 확인해봤습니다. lombok이 boolean 타입을 isXX로 생성하는데 그러면 @RequestBody에서 get메서드를 찾을 수 없어서 제대로 바인딩 되지 않고 디폴트 값인 false가 들어가는 문제입니다.

해결법으론 여러가지가 있는데 타입을 Boolean 으로 변경하는 것입니다.
Boolean의 경우 lombok이 메서드를 getIsXX 로 만들어 줘서 그때는 바인딩이 가능해 집니다.
대신 자동생성 되는 메서드가 isXX가 아니라 getISXX 로 생성됩니다.

![image](https://github.com/FC-BE-ToyProject-Team6/KDT_Y_BE_Toy_Project2_DEV/assets/40512982/4bbf9b03-886e-49af-be8e-829385c05aee)


![image](https://github.com/FC-BE-ToyProject-Team6/KDT_Y_BE_Toy_Project2_DEV/assets/40512982/a003d1f3-4bb3-4264-9c43-6ad921e02cc0)

위처럼 수정했을 경우 true로 데이터가 바인딩 됩니다.

엔티티의 boolean도 Boolean 타입으로 변경하도록 하겠습니다.

2023-10-24 11:05 UTC, whdgns5059 commented on src/main/java/com/fastcampus/toyproject/domain/trip/entity/Trip.java
> +@Setter
DTO, Entity에서 @Setter는 위험 할 것 같습니다.

2023-10-24 11:05 UTC, whdgns5059 commented on src/main/java/com/fastcampus/toyproject/domain/trip/service/TripService.java
> +            .isDomestic(tripDTO.isDomestic())
위에서 말씀드린 lombok 과 requestBody 문제때문에 DTO 타입을 Boolean으로 바꾸면 getIsDomestic() 으로 사용할 수 있습니다.

2023-10-24 11:22 UTC, whdgns5059 commented on src/main/java/com/fastcampus/toyproject/domain/trip/service/TripService.java
> +            throw new DefaultException(ExceptionCode.INVALID_REQUEST, "해당하는 Trip이 없습니다.");
아래에서 중복되는 Exception 코드가 있어서 "해당하는 Trip이 없습니다" 메시지를 문자열로 작성하는 것보다
trip.exception 패키지에서 enum으로 TripExceptionCode를 만들어서 
NO_SUCH_TRIP_EXCEPTION("해당 하는 Trip이 없습니다") 처럼 enum으로 
관리 하는게 좋을 것 같습니다.

2023-10-25 01:02 UTC, sungjiwoon approved these changes
감사합니다.

2023-10-25 01:02 UTC, whdgns5059 approved these changes

2023-10-25 01:03 UTC, merged

2023-10-25 04:54 UTC, ghrltjdtprbs commented on src/main/java/com/fastcampus/toyproject/domain/trip/dto/TripDTO.java
> +@Setter
수정해서 pr올렸습니다!

2023-10-25 04:54 UTC, ghrltjdtprbs commented on src/main/java/com/fastcampus/toyproject/domain/trip/dto/TripDTO.java
> +    private boolean isDomestic;
덕분에 오류 해결했습니다! 감사해요 ㅎㅎ😊

2023-10-25 04:55 UTC, ghrltjdtprbs commented on src/main/java/com/fastcampus/toyproject/domain/trip/service/TripService.java
> +            throw new DefaultException(ExceptionCode.INVALID_REQUEST, "해당하는 Trip이 없습니다.");
최대한 반영하겠습니다!